version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: expoMultiMix
      MYSQL_USER: root
      MYSQL_PASSWORD: '12345'
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql